alter table SCHEDULE_CLASSROOM add constraint FK_SCHEDULE_CLASSROOM_ON_LESSON foreign key (LESSON_ID) references SCHEDULE_LESSON(ID);
create index IDX_SCHEDULE_CLASSROOM_ON_LESSON on SCHEDULE_CLASSROOM (LESSON_ID);
