alter table SCHEDULE_LESSON add constraint FK_SCHEDULE_LESSON_ON_CLASSROOM foreign key (CLASSROOM_ID) references SCHEDULE_CLAASSROOM(ID);
create index IDX_SCHEDULE_LESSON_ON_CLASSROOM on SCHEDULE_LESSON (CLASSROOM_ID);
