alter table SCHEDULE_STUDENT add constraint FK_SCHEDULE_STUDENT_ON_GROUP foreign key (GROUP_ID) references SCHEDULE_GROUP(ID);
create index IDX_SCHEDULE_STUDENT_ON_GROUP on SCHEDULE_STUDENT (GROUP_ID);
