-- begin SCHEDULE_STUDENT
alter table SCHEDULE_STUDENT add constraint FK_SCHEDULE_STUDENT_ON_GROUP foreign key (GROUP_ID) references SCHEDULE_GROUP(ID)^
create unique index IDX_SCHEDULE_STUDENT_UK_GRADE_BOOK on SCHEDULE_STUDENT (GRADE_BOOK) where DELETE_TS is null ^
create index IDX_SCHEDULE_STUDENT_ON_GROUP on SCHEDULE_STUDENT (GROUP_ID)^
create index IDX_SCHEDULE_STUDENT_FULL_NAME on SCHEDULE_STUDENT (FULL_NAME)^
-- end SCHEDULE_STUDENT
-- begin SCHEDULE_GROUP
create unique index IDX_SCHEDULE_GROUP_UK_GROUP_NUMBER on SCHEDULE_GROUP (GROUP_NUMBER) where DELETE_TS is null ^
-- end SCHEDULE_GROUP

-- begin SCHEDULE_LESSON
alter table SCHEDULE_LESSON add constraint FK_SCHEDULE_LESSON_ON_TEACHER foreign key (TEACHER_ID) references SCHEDULE_TEACHER(ID)^
alter table SCHEDULE_LESSON add constraint FK_SCHEDULE_LESSON_ON_GROUP foreign key (GROUP_ID) references SCHEDULE_GROUP(ID)^
alter table SCHEDULE_LESSON add constraint FK_SCHEDULE_LESSON_ON_CLASSROOM foreign key (CLASSROOM_ID) references SCHEDULE_CLASSROOM(ID)^
create index IDX_SCHEDULE_LESSON_ON_TEACHER on SCHEDULE_LESSON (TEACHER_ID)^
create index IDX_SCHEDULE_LESSON_ON_GROUP on SCHEDULE_LESSON (GROUP_ID)^
create index IDX_SCHEDULE_LESSON_ON_CLASSROOM on SCHEDULE_LESSON (CLASSROOM_ID)^
-- end SCHEDULE_LESSON
-- begin SCHEDULE_TEACHER
create unique index IDX_SCHEDULE_TEACHER_UK_EMAIL on SCHEDULE_TEACHER (EMAIL) where DELETE_TS is null ^
-- end SCHEDULE_TEACHER
-- begin SCHEDULE_CLASSROOM
create unique index IDX_SCHEDULE_CLASSROOM_UK_NUMBER_ on SCHEDULE_CLASSROOM (NUMBER_) where DELETE_TS is null ^
-- end SCHEDULE_CLASSROOM
